#!/usr/bin/env python3
"""Build a JSON mapping from each metric (as listed in the source CSV) to the
area > subarea locations where it is presented in the taxonomy.

Usage:
    python3 scripts/build-metric-subarea-map.py

Reads:
    scripts/metrics-source.csv  (columns: benchmark,metric_id,metric_name)
    static/data/taxonomy.json

Writes:
    static/data/metric-subarea-map.json
"""
from __future__ import annotations

import csv
import json
import re
from collections import defaultdict
from pathlib import Path

TOOLS = Path(__file__).resolve().parent
ROOT = TOOLS.parent
BENCHMARKS = ROOT / "benchmarks"
CSV_PATH = TOOLS / "metrics-source.csv"
TAXONOMY_PATH = BENCHMARKS / "taxonomy.json"
OUT_PATH = TOOLS / "_out" / "metric-subarea-map.json"

# Benchmark names in the CSV do not always slugify identically to the prefixes
# used inside taxonomy.json (which were generated by a separate pipeline).
# These overrides handle the known mismatches.
BENCHMARK_SLUG_OVERRIDES = {
    "Cultural Context Sensitivity in AI-Mediated Knowledge Production":
        "construct-cultural-context-sensitivity-in-ai-mediated-knowledge-production",
    "HumanAgencyBench": "humanagency-bench",
    "MCAB": "modulated-cognitive-autonomy-benchmark-mcab",
}


def slugify(name: str) -> str:
    s = name.lower()
    s = s.replace("&", "and")
    s = re.sub(r"[^a-z0-9]+", "-", s)
    return s.strip("-")


def build_taxonomy_index(taxonomy: dict) -> dict[str, list[dict]]:
    """metric_id -> list of {area, area_name, subarea, subarea_name}."""
    index: dict[str, list[dict]] = defaultdict(list)
    for area in taxonomy["areas"]:
        for sub in area["subareas"]:
            for m in sub["metrics"]:
                index[m["id"]].append({
                    "area": area["id"],
                    "area_name": area["name"],
                    "subarea": sub["id"],
                    "subarea_name": sub["name"],
                })
    return index


def main() -> None:
    with TAXONOMY_PATH.open() as f:
        taxonomy = json.load(f)
    tax_index = build_taxonomy_index(taxonomy)

    entries: list[dict] = []
    unmatched_benchmarks: set[str] = set()
    unplaced_metrics: list[str] = []

    with CSV_PATH.open() as f:
        for row in csv.DictReader(f):
            benchmark = row["benchmark"].strip()
            metric_short = row["metric_id"].strip()
            metric_name = row["metric_name"].strip()

            slug = BENCHMARK_SLUG_OVERRIDES.get(benchmark) or slugify(benchmark)
            full_id = f"{slug}__{metric_short}"
            placements = tax_index.get(full_id, [])

            if not placements:
                # Track diagnostics but still emit the row with empty placements.
                if not any(k.startswith(f"{slug}__") for k in tax_index):
                    unmatched_benchmarks.add(benchmark)
                else:
                    unplaced_metrics.append(full_id)

            entries.append({
                "benchmark": benchmark,
                "benchmark_slug": slug,
                "metric_id": full_id,
                "metric_short_id": metric_short,
                "metric_name": metric_name,
                "placements": placements,
            })

    # Also emit a grouped view keyed by area > subarea for quick browsing.
    grouped: dict[str, dict[str, list[dict]]] = defaultdict(lambda: defaultdict(list))
    for e in entries:
        for p in e["placements"]:
            grouped[p["area_name"]][p["subarea_name"]].append({
                "metric_id": e["metric_id"],
                "metric_name": e["metric_name"],
                "benchmark": e["benchmark"],
            })

    output = {
        "generated_from": {
            "csv": str(CSV_PATH.relative_to(ROOT)),
            "taxonomy": str(TAXONOMY_PATH.relative_to(ROOT)),
        },
        "metrics": entries,
        "by_area_subarea": grouped,
    }

    OUT_PATH.write_text(json.dumps(output, indent=2) + "\n")

    total = len(entries)
    placed = sum(1 for e in entries if e["placements"])
    print(f"Wrote {OUT_PATH.relative_to(ROOT)}")
    print(f"  {placed}/{total} metrics have taxonomy placements")
    if unmatched_benchmarks:
        print("  Benchmarks with no matching slug in taxonomy:")
        for b in sorted(unmatched_benchmarks):
            print(f"    - {b}")
    if unplaced_metrics:
        print(f"  Individual metrics with a matching benchmark but no placement: {len(unplaced_metrics)}")
        for m in unplaced_metrics[:10]:
            print(f"    - {m}")


if __name__ == "__main__":
    main()
